# Generated by Django 4.0.4 on 2022-05-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='createAt',
            new_name='createdAt',
        ),
    ]
