# Generated by Django 4.0.4 on 2022-11-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_orderitem_size_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[(' ', 'Zero'), ('XS', 'Xs'), ('S', 'S'), ('M', 'M'), ('XL', 'Xl')], default=' ', max_length=2),
        ),
    ]
