# Generated by Django 4.0.4 on 2022-11-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'Xs'), ('S', 'S'), ('M', 'M'), ('XL', 'Xl')], default='XS', max_length=2),
        ),
    ]
