# Generated by Django 4.0.4 on 2022-11-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
